apiVersion: v1
kind: Template
labels:
  app: ${APP_NAME}-cd
  
metadata:
  annotations:
    iconClass: icon-jenkins
    tags: instant-app,jenkins,gogs,nexus,cicd
  name: avaya-cd
message: "Use the following credentials for login:\nJenkins: use your OpenShift credentials"
parameters:
- displayName: Source project name
  name: SOURCE_PROJECT
  required: true
- displayName: Destination project name
  name: DEST_PROJECT
  required: true
- displayName: CICD project name
  name: CICD_PROJECT
  required: true
  value: avaya-cicd
- displayName: Applicaton name
  name: APP_NAME
  required: true
- displayName: Repository url
  name: REPO_URL
  required: true
- displayName: Repository reference
  name: REPO_REF
  value: main 
- description: Webhook secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: WEBHOOK_SECRET
  required: true
- displayName: Image name
  name: IMAGE_NAME
  required: true
- displayName: source image tag
  name: SOURCE_IMAGE_TAG
  value: stage
  required: true  
- displayName: destination image tag
  name: DEST_IMAGE_TAG
  required: true  



objects:

# Pipeline

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: edit-${DEST_PROJECT}
    namespace: ${CICD_PROJECT}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:${DEST_PROJECT}



- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
    labels:
      app: ${APP_NAME}-deployment-pipeline
      name: ${APP_NAME}-deployment-pipeline
    name: ${APP_NAME}-deployment-pipeline
    namespace: ${CICD_PROJECT}
  spec:
    triggers:
      - type: GitHub
        github:
          secret: ${WEBHOOK_SECRET}
      - type: Generic
        generic:
          secret: ${WEBHOOK_SECRET}
    runPolicy: Serial
    source:
      type: "Git"
      git:
        uri: ${REPO_URL}
        ref: ${REPO_REF}
      sourceSecret:
        name: git-secret
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: SOURCE_PROJECT
          value: ${DEV_PROJECT}
        - name: DEST_PROJECT
          value: ${STAGE_PROJECT}
        - name: APP_NAME
          value: ${APP_NAME}
        - name: IMAGE_NAME
          value: ${IMAGE_NAME}
        - name: SOURCE_IMAGE_TAG
          value: ${SOURCE_IMAGE_TAG}
        - name: DEST_IMAGE_TAG
          value: ${DEST_IMAGE_TAG}
        jenkinsfilePath: cicd/Jenkinsfile
      type: JenkinsPipeline
