apiVersion: v1
kind: Template
labels:
  app: ${DEST_APP_NAME}-cd
  avaya-pipeline: batch-deployment
  
metadata:
  annotations:
    iconClass: icon-jenkins
    tags: instant-app,jenkins,gogs,nexus,cicd
  name: avaya-cd
message: "Use the following credentials for login:\nJenkins: use your OpenShift credentials"
parameters:
- displayName: Source project name
  name: SOURCE_PROJECT
  required: true
- displayName: Destination project name
  name: DEST_PROJECT
  required: true
- displayName: CICD project name
  name: CICD_PROJECT
  required: true
  value: avaya-cicd
- displayName: Source Applicaton name
  name: SOURCE_APP_NAME
  required: true
- displayName: Destination Applicaton name
  name: DEST_APP_NAME
  required: true
- displayName: Repository url
  name: REPO_URL
  required: true
- displayName: Repository reference
  name: REPO_REF
  value: main 
- description: Webhook secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: WEBHOOK_SECRET
  required: true
- displayName: Image name
  name: IMAGE_NAME
  required: true
- displayName: source image tag
  name: SOURCE_IMAGE_TAG
  value: stage
  required: true  
- displayName: destination image tag
  name: DEST_IMAGE_TAG
  required: true  



objects:

# Pipeline



- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
    labels:
      app: ${DEST_APP_NAME}-deployment-pipeline
      name: ${DEST_APP_NAME}-deployment-pipeline
    name: ${DEST_APP_NAME}-deployment-pipeline
    namespace: ${CICD_PROJECT}
  spec:
    triggers:
      - type: GitHub
        github:
          secret: ${WEBHOOK_SECRET}
      - type: Generic
        generic:
          secret: ${WEBHOOK_SECRET}
    runPolicy: Serial
    source:
      type: "Git"
      git:
        uri: ${REPO_URL}
        ref: ${REPO_REF}
      sourceSecret:
        name: git-secret
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: SOURCE_PROJECT
          value: ${SOURCE_PROJECT}
        - name: DEST_PROJECT
          value: ${DEST_PROJECT}
        - name: SOURCE_APP_NAME
          value: ${SOURCE_APP_NAME}
        - name: DEST_APP_NAME
          value: ${DEST_APP_NAME}
        - name: IMAGE_NAME
          value: ${IMAGE_NAME}
        - name: SOURCE_IMAGE_TAG
          value: ${SOURCE_IMAGE_TAG}
        - name: DEST_IMAGE_TAG
          value: ${DEST_IMAGE_TAG}
        jenkinsfilePath: cicd/Jenkinsfile-cd	
       
      type: JenkinsPipeline
